# Generated by Django 4.2.1 on 2023-06-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_prod', models.CharField(max_length=20)),
                ('valor_prod', models.IntegerField()),
                ('imagen_prod', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(db_column='idTipoUsuario', primary_key=True, serialize=False)),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nro_usuario', models.AutoField(db_column='Usuario', primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('p_nombre', models.CharField(max_length=30)),
                ('s_nombre', models.CharField(max_length=30)),
                ('a_paterno', models.CharField(max_length=30)),
                ('a_materno', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=30)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='tienda.genero')),
                ('id_tipo_usuario', models.ForeignKey(db_column='idTipoUsuario', on_delete=django.db.models.deletion.CASCADE, to='tienda.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('nro_compra', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('nro_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('nro_item', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor_item', models.IntegerField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('nro_compra', models.OneToOneField(db_column='nro_compra', on_delete=django.db.models.deletion.CASCADE, to='tienda.compra')),
            ],
            options={
                'unique_together': {('nro_compra', 'nro_item')},
            },
        ),
    ]
