# Generated by Django 4.2.1 on 2023-06-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_detallecompra_nro_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=1000),
        ),
    ]
