# Generated by Django 4.2.1 on 2023-06-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_prod',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=20),
        ),
    ]
