# Generated by Django 4.2.1 on 2023-06-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_tipoproducto_rename_a_materno_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=60),
        ),
    ]
