# Generated by Django 4.2.1 on 2023-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_tipoproducto_id_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_prod',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
